# drawing.py
from typing import Tuple, Optional, List

# Direction bitmasks (matching generator.py)
N = 1
E = 2
S = 4
W = 8


class AsciiRenderer:
    """
    Draws a maze generated by MazeGenerator (bitmask grid),
    keeping the 42-block cells fully blocked.
    """

    def __init__(self, maze, entry: Tuple[int, int], exit: Tuple[int, int]):
        self.maze = maze
        self.entry = entry
        self.exit = exit

    @staticmethod
    def cells_of_42(wd: int, ht: int) -> List[Tuple[int, int]]:
        cx = wd // 2
        cy = ht // 2

        cells = [
            (cx + 2, cy - 2), (cx + 1, cy - 2), (cx + 3, cy - 2),
            (cx + 3, cy - 1), (cx + 3, cy), (cx + 2, cy),
            (cx + 1, cy), (cx + 1, cy + 1), (cx + 1, cy + 2),
            (cx + 2, cy + 2), (cx + 3, cy + 2),

            (cx - 3, cy - 2), (cx - 3, cy - 1), (cx - 3, cy),
            (cx - 2, cy), (cx - 1, cy),
            (cx - 1, cy + 1), (cx - 1, cy + 2)
        ]

        return [(x, y) for x, y in cells if 0 <= x < wd and 0 <= y < ht]

    def render(
        self,
        player_pos: Optional[Tuple[int, int]] = None,
        visited_trail: Optional[List] = None,
        path: Optional[List[Tuple[int, int]]] = None,
        show: bool = True
    ) -> str:

        BLOCK = "█"
        width = self.maze.width
        height = self.maze.height
        grid = self.maze.grid
        h_seg = BLOCK * 3

        output = ""

        # Top border
        output += BLOCK + (h_seg + BLOCK) * (width - 1) + h_seg + BLOCK + "\n"

        cell42 = set(self.cells_of_42(width, height))

        for y in range(height):

            row_str = BLOCK

            for x in range(width):

                cell = grid[y][x]

                # Force 42-block cells fully closed
                if (x, y) in cell42:
                    cell |= N | E | S | W

                # Decide body character
                if (x, y) == self.entry:
                    body = " 🐹"
                elif (x, y) == self.exit:
                    body = " 🚪"
                elif (x, y) in cell42:
                    body = " 🔥"
                elif path and (x, y) in path:
                    body = " ⋅ "
                else:
                    body = "   "

                # East wall
                wall_char = BLOCK if (cell & E) != 0 or x == width - 1 else " "
                row_str += body + wall_char

            output += row_str + "\n"

            if y < height - 1:

                row_str = BLOCK

                for x in range(width):

                    cell = grid[y][x]

                    # Force 42-block cells fully closed
                    if (x, y) in cell42:
                        cell |= N | E | S | W

                    # South wall
                    wall = h_seg if (cell & S) != 0 else "   "
                    row_str += wall + BLOCK

                output += row_str + "\n"

        # Bottom border
        output += BLOCK + (h_seg + BLOCK) * (width - 1) + h_seg + BLOCK + "\n"

        return output


